import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import Providers from "./components/Providers";
// import Header from "./components/Header/Header";
// import Footer from "./components/Footer/Footer";

const cairo = Cairo({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  );
}
